version: "3"

services:
  app:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
      - memcached

  db:
    image: postgres:10-alpine
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  memcached:
    image: memcached:1.6-alpine
    expose:
      - 11211
    environment:
      - CACHE_SIZE=128
      - MAX_CONNECTIONS=2000


volumes:
  postgres_data: